language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
